/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_voltdb_jni_ExecutionEngine */

#ifndef _Included_org_voltdb_jni_ExecutionEngine
#define _Included_org_voltdb_jni_ExecutionEngine
#ifdef __cplusplus
extern "C" {
#endif
#undef org_voltdb_jni_ExecutionEngine_ERRORCODE_SUCCESS
#define org_voltdb_jni_ExecutionEngine_ERRORCODE_SUCCESS 0L
#undef org_voltdb_jni_ExecutionEngine_ERRORCODE_ERROR
#define org_voltdb_jni_ExecutionEngine_ERRORCODE_ERROR 1L
#undef org_voltdb_jni_ExecutionEngine_ERRORCODE_WRONG_SERIALIZED_BYTES
#define org_voltdb_jni_ExecutionEngine_ERRORCODE_WRONG_SERIALIZED_BYTES 101L
#undef org_voltdb_jni_ExecutionEngine_ERRORCODE_NEED_PLAN
#define org_voltdb_jni_ExecutionEngine_ERRORCODE_NEED_PLAN 110L
#undef org_voltdb_jni_ExecutionEngine_ERRORCODE_PROGRESS_UPDATE
#define org_voltdb_jni_ExecutionEngine_ERRORCODE_PROGRESS_UPDATE 111L
#undef org_voltdb_jni_ExecutionEngine_ERRORCODE_DECODE_BASE64_AND_DECOMPRESS
#define org_voltdb_jni_ExecutionEngine_ERRORCODE_DECODE_BASE64_AND_DECOMPRESS 112L
#undef org_voltdb_jni_ExecutionEngine_EE_PLAN_CACHE_SIZE
#define org_voltdb_jni_ExecutionEngine_EE_PLAN_CACHE_SIZE 1000L
#undef org_voltdb_jni_ExecutionEngine_LONG_OP_THRESHOLD
#define org_voltdb_jni_ExecutionEngine_LONG_OP_THRESHOLD 10000LL
#undef org_voltdb_jni_ExecutionEngine_NO_BATCH_TIMEOUT_VALUE
#define org_voltdb_jni_ExecutionEngine_NO_BATCH_TIMEOUT_VALUE 0L
/*
 * Class:     org_voltdb_jni_ExecutionEngine
 * Method:    nextDependencyTest
 * Signature: (I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_voltdb_jni_ExecutionEngine_nextDependencyTest
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_voltdb_jni_ExecutionEngine
 * Method:    nativeCreate
 * Signature: (Z)J
 */
JNIEXPORT jlong JNICALL Java_org_voltdb_jni_ExecutionEngine_nativeCreate
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_voltdb_jni_ExecutionEngine
 * Method:    nativeDestroy
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_voltdb_jni_ExecutionEngine_nativeDestroy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_voltdb_jni_ExecutionEngine
 * Method:    nativeDecommission
 * Signature: (JZZI)I
 */
JNIEXPORT jint JNICALL Java_org_voltdb_jni_ExecutionEngine_nativeDecommission
  (JNIEnv *, jobject, jlong, jboolean, jboolean, jint);

/*
 * Class:     org_voltdb_jni_ExecutionEngine
 * Method:    nativeInitialize
 * Signature: (JIJIII[BIIZIZJZI)I
 */
JNIEXPORT jint JNICALL Java_org_voltdb_jni_ExecutionEngine_nativeInitialize
  (JNIEnv *, jobject, jlong, jint, jlong, jint, jint, jint, jbyteArray, jint, jint, jboolean, jint, jboolean, jlong, jboolean, jint);

/*
 * Class:     org_voltdb_jni_ExecutionEngine
 * Method:    nativeSetBuffers
 * Signature: (JLjava/nio/ByteBuffer;ILjava/nio/ByteBuffer;ILjava/nio/ByteBuffer;ILjava/nio/ByteBuffer;ILjava/nio/ByteBuffer;ILjava/nio/ByteBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_org_voltdb_jni_ExecutionEngine_nativeSetBuffers
  (JNIEnv *, jobject, jlong, jobject, jint, jobject, jint, jobject, jint, jobject, jint, jobject, jint, jobject, jint);

/*
 * Class:     org_voltdb_jni_ExecutionEngine
 * Method:    nativeLoadCatalog
 * Signature: (JJ[B)I
 */
JNIEXPORT jint JNICALL Java_org_voltdb_jni_ExecutionEngine_nativeLoadCatalog
  (JNIEnv *, jobject, jlong, jlong, jbyteArray);

/*
 * Class:     org_voltdb_jni_ExecutionEngine
 * Method:    nativeUpdateCatalog
 * Signature: (JJZ[B)I
 */
JNIEXPORT jint JNICALL Java_org_voltdb_jni_ExecutionEngine_nativeUpdateCatalog
  (JNIEnv *, jobject, jlong, jlong, jboolean, jbyteArray);

/*
 * Class:     org_voltdb_jni_ExecutionEngine
 * Method:    nativeLoadTable
 * Signature: (JI[BJJJJJB)I
 */
JNIEXPORT jint JNICALL Java_org_voltdb_jni_ExecutionEngine_nativeLoadTable__JI_3BJJJJJB
  (JNIEnv *, jobject, jlong, jint, jbyteArray, jlong, jlong, jlong, jlong, jlong, jbyte);

/*
 * Class:     org_voltdb_jni_ExecutionEngine
 * Method:    nativeLoadTable
 * Signature: (JILjava/nio/ByteBuffer;JJJJJB)I
 */
JNIEXPORT jint JNICALL Java_org_voltdb_jni_ExecutionEngine_nativeLoadTable__JILjava_nio_ByteBuffer_2JJJJJB
  (JNIEnv *, jobject, jlong, jint, jobject, jlong, jlong, jlong, jlong, jlong, jbyte);

/*
 * Class:     org_voltdb_jni_ExecutionEngine
 * Method:    nativeExecutePlanFragments
 * Signature: (JII[J[JJJJJJZ)I
 */
JNIEXPORT jint JNICALL Java_org_voltdb_jni_ExecutionEngine_nativeExecutePlanFragments
  (JNIEnv *, jobject, jlong, jint, jint, jlongArray, jlongArray, jlong, jlong, jlong, jlong, jlong, jboolean);

/*
 * Class:     org_voltdb_jni_ExecutionEngine
 * Method:    nativeSerializeTable
 * Signature: (JILjava/nio/ByteBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_org_voltdb_jni_ExecutionEngine_nativeSerializeTable
  (JNIEnv *, jobject, jlong, jint, jobject, jint);

/*
 * Class:     org_voltdb_jni_ExecutionEngine
 * Method:    nativeTick
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_voltdb_jni_ExecutionEngine_nativeTick
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     org_voltdb_jni_ExecutionEngine
 * Method:    nativeQuiesce
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_voltdb_jni_ExecutionEngine_nativeQuiesce
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_voltdb_jni_ExecutionEngine
 * Method:    nativeGetStats
 * Signature: (JI[IZJ)I
 */
JNIEXPORT jint JNICALL Java_org_voltdb_jni_ExecutionEngine_nativeGetStats
  (JNIEnv *, jobject, jlong, jint, jintArray, jboolean, jlong);

/*
 * Class:     org_voltdb_jni_ExecutionEngine
 * Method:    nativeToggleProfiler
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_voltdb_jni_ExecutionEngine_nativeToggleProfiler
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_voltdb_jni_ExecutionEngine
 * Method:    nativeHashinate
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_org_voltdb_jni_ExecutionEngine_nativeHashinate
  (JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     org_voltdb_jni_ExecutionEngine
 * Method:    nativeUpdateHashinator
 * Signature: (JJI)V
 */
JNIEXPORT void JNICALL Java_org_voltdb_jni_ExecutionEngine_nativeUpdateHashinator
  (JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     org_voltdb_jni_ExecutionEngine
 * Method:    nativeGetThreadLocalPoolAllocations
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_voltdb_jni_ExecutionEngine_nativeGetThreadLocalPoolAllocations
  (JNIEnv *, jclass);

/*
 * Class:     org_voltdb_jni_ExecutionEngine
 * Method:    nativeSetUndoToken
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_voltdb_jni_ExecutionEngine_nativeSetUndoToken
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_voltdb_jni_ExecutionEngine
 * Method:    nativeReleaseUndoToken
 * Signature: (JJZ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_voltdb_jni_ExecutionEngine_nativeReleaseUndoToken
  (JNIEnv *, jobject, jlong, jlong, jboolean);

/*
 * Class:     org_voltdb_jni_ExecutionEngine
 * Method:    nativeUndoUndoToken
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_voltdb_jni_ExecutionEngine_nativeUndoUndoToken
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_voltdb_jni_ExecutionEngine
 * Method:    nativeSetLogLevels
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_voltdb_jni_ExecutionEngine_nativeSetLogLevels
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_voltdb_jni_ExecutionEngine
 * Method:    nativeGetSnapshotSchema
 * Signature: (JIBZ)I
 */
JNIEXPORT jint JNICALL Java_org_voltdb_jni_ExecutionEngine_nativeGetSnapshotSchema
  (JNIEnv *, jobject, jlong, jint, jbyte, jboolean);

/*
 * Class:     org_voltdb_jni_ExecutionEngine
 * Method:    nativeActivateTableStream
 * Signature: (JIIBJ[B)Z
 */
JNIEXPORT jboolean JNICALL Java_org_voltdb_jni_ExecutionEngine_nativeActivateTableStream
  (JNIEnv *, jobject, jlong, jint, jint, jbyte, jlong, jbyteArray);

/*
 * Class:     org_voltdb_jni_ExecutionEngine
 * Method:    nativeTableStreamSerializeMore
 * Signature: (JII[B)J
 */
JNIEXPORT jlong JNICALL Java_org_voltdb_jni_ExecutionEngine_nativeTableStreamSerializeMore
  (JNIEnv *, jobject, jlong, jint, jint, jbyteArray);

/*
 * Class:     org_voltdb_jni_ExecutionEngine
 * Method:    nativeTableHashCode
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_org_voltdb_jni_ExecutionEngine_nativeTableHashCode
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_voltdb_jni_ExecutionEngine
 * Method:    nativeApplyBinaryLog
 * Signature: (JJJJJIJ)J
 */
JNIEXPORT jlong JNICALL Java_org_voltdb_jni_ExecutionEngine_nativeApplyBinaryLog
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jlong, jint, jlong);

/*
 * Class:     org_voltdb_jni_ExecutionEngine
 * Method:    nativeExecuteTask
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_voltdb_jni_ExecutionEngine_nativeExecuteTask
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_voltdb_jni_ExecutionEngine
 * Method:    nativeSetExportStreamPositions
 * Signature: (JJJJ[B)V
 */
JNIEXPORT void JNICALL Java_org_voltdb_jni_ExecutionEngine_nativeSetExportStreamPositions
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jbyteArray);

/*
 * Class:     org_voltdb_jni_ExecutionEngine
 * Method:    nativeDeleteMigratedRows
 * Signature: (JJJJ[BJJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_voltdb_jni_ExecutionEngine_nativeDeleteMigratedRows
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jbyteArray, jlong, jlong);

/*
 * Class:     org_voltdb_jni_ExecutionEngine
 * Method:    nativeSetViewsEnabled
 * Signature: (J[BZ)V
 */
JNIEXPORT void JNICALL Java_org_voltdb_jni_ExecutionEngine_nativeSetViewsEnabled
  (JNIEnv *, jobject, jlong, jbyteArray, jboolean);

/*
 * Class:     org_voltdb_jni_ExecutionEngine
 * Method:    nativeDisableExternalStreams
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_voltdb_jni_ExecutionEngine_nativeDisableExternalStreams
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_voltdb_jni_ExecutionEngine
 * Method:    nativeExternalStreamsEnabled
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_voltdb_jni_ExecutionEngine_nativeExternalStreamsEnabled
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_voltdb_jni_ExecutionEngine
 * Method:    nativeGetUSOForExportTable
 * Signature: (J[B)[J
 */
JNIEXPORT jlongArray JNICALL Java_org_voltdb_jni_ExecutionEngine_nativeGetUSOForExportTable
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     org_voltdb_jni_ExecutionEngine
 * Method:    nativeGetRSS
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_voltdb_jni_ExecutionEngine_nativeGetRSS
  (JNIEnv *, jclass);

/*
 * Class:     org_voltdb_jni_ExecutionEngine
 * Method:    getTestDRBuffer
 * Signature: (II[I[IJ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_voltdb_jni_ExecutionEngine_getTestDRBuffer
  (JNIEnv *, jclass, jint, jint, jintArray, jintArray, jlong);

/*
 * Class:     org_voltdb_jni_ExecutionEngine
 * Method:    nativeStoreTopicsGroup
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_voltdb_jni_ExecutionEngine_nativeStoreTopicsGroup
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_voltdb_jni_ExecutionEngine
 * Method:    nativeDeleteTopicsGroup
 * Signature: (JJ[B)I
 */
JNIEXPORT jint JNICALL Java_org_voltdb_jni_ExecutionEngine_nativeDeleteTopicsGroup
  (JNIEnv *, jclass, jlong, jlong, jbyteArray);

/*
 * Class:     org_voltdb_jni_ExecutionEngine
 * Method:    nativeFetchTopicsGroups
 * Signature: (JI[B)I
 */
JNIEXPORT jint JNICALL Java_org_voltdb_jni_ExecutionEngine_nativeFetchTopicsGroups
  (JNIEnv *, jclass, jlong, jint, jbyteArray);

/*
 * Class:     org_voltdb_jni_ExecutionEngine
 * Method:    nativeCommitTopicsGroupOffsets
 * Signature: (JJJS[B)I
 */
JNIEXPORT jint JNICALL Java_org_voltdb_jni_ExecutionEngine_nativeCommitTopicsGroupOffsets
  (JNIEnv *, jclass, jlong, jlong, jlong, jshort, jbyteArray);

/*
 * Class:     org_voltdb_jni_ExecutionEngine
 * Method:    nativeFetchTopicsGroupOffsets
 * Signature: (JS[B)I
 */
JNIEXPORT jint JNICALL Java_org_voltdb_jni_ExecutionEngine_nativeFetchTopicsGroupOffsets
  (JNIEnv *, jclass, jlong, jshort, jbyteArray);

/*
 * Class:     org_voltdb_jni_ExecutionEngine
 * Method:    nativeDeleteExpiredTopicsOffsets
 * Signature: (JJJ)I
 */
JNIEXPORT jint JNICALL Java_org_voltdb_jni_ExecutionEngine_nativeDeleteExpiredTopicsOffsets
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_voltdb_jni_ExecutionEngine
 * Method:    nativeSetReplicableTables
 * Signature: (JI[[B)I
 */
JNIEXPORT jint JNICALL Java_org_voltdb_jni_ExecutionEngine_nativeSetReplicableTables
  (JNIEnv *, jclass, jlong, jint, jobjectArray);

/*
 * Class:     org_voltdb_jni_ExecutionEngine
 * Method:    nativeClearAllReplicableTables
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_voltdb_jni_ExecutionEngine_nativeClearAllReplicableTables
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_voltdb_jni_ExecutionEngine
 * Method:    nativeClearReplicableTables
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_voltdb_jni_ExecutionEngine_nativeClearReplicableTables
  (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
